version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api:2.0
    build:
      context: .
      dockerfile: api/Dockerfile
    networks: 
     - nginxproxymanager_default
 
networks:
  nginxproxymanager_default:
    driver: bridge
 
